export const LOADING = 'LOADING'
export const ERROR = 'ERROR'
export const FORMDATA = 'FORMDATA'
export const NOTIFICATIONS = 'NOTIFICATIONS'
export const SET_ISSUES = 'SET_ISSUES'

// LOGIN
export const LOGIN_FORM = 'LOGIN_FORM'
export const EDIT_INFO_FORM = 'EDIT_INFO_FORM'
export const GET_USER = 'GET_USER'

// EDIT PROFILE
export const FETCH_PROFILE = 'FETCH_PROFILE'
export const PROFILE_FORM = 'PROFILE_FORM'
export const EDIT_PROFILE = 'EDIT_PROFILE'
export const EDIT_SETTINGS = 'EDIT_SETTINGS'
export const SET_CODE = 'SET_CODE'

// DASHBOARD
export const FETCH_DASHBOARD = 'FETCH_DASHBOARD'

// INFORMATION SECTION
export const GET_INFOCARDS = 'GET_INFOCARDS'

// REQUESTS
export const FETCH_REQUESTS = 'FETCH_REQUESTS'
export const GET_REQUEST_DETAILS = 'GET_REQUEST_DETAILS'
export const REQUEST_FORM = 'REQUEST_FORM'
export const POST_REQUEST = 'POST_REQUEST'
export const GET_ROLES = 'GET_ROLES'

// DEBTS
export const GET_DEBTS = 'GET_DEBTS'
export const GET_PAYED_DEBTS = 'GET_PAYED_DEBTS'

// VISITS
export const GET_VISITS = 'GET_VISITS'
export const GET_VISITS_DETAILS = 'GET_VISITS_DETAILS'
export const REQUEST_VISIT = 'REQUEST_VISIT'
export const GET_VISIT_BIO = 'GET_VISIT_BIO'

// REPORTS & BINNALE'S
export const GET_REPORTS = 'GET_REPORTS'
export const GET_BINNACLES = 'GET_BINNACLES'

// IRRIGATOR DETAIL
export const GET_IRRIGATOR = 'GET_IRRIGATOR'
export const GET_HISTORY = 'GET_HISTORY'
